### ISSUE TITLE
距離空間を位相空間に拡張する動機を明確にしたい

### ISSUE THREAD

**Issue by shiba-dog-leo** [Y-Naka-implicit/ynu-math.github.io#8]
距離空間を位相空間に拡張する動機を明確にしたい

**Comment by shiba-dog-leo** [comment]
距離空間の持つ性質を特徴づけると開集合の公理への示唆が得られますね

**Comment by Y-Naka-implicit** [comment]
https://github.com/Y-Naka-implicit/ynu-math.github.io/commit/21bece7fb36c9a4a0fd577ff11c2b84fc9cbcafd

節を追加してpushしました．

**Comment by shiba-dog-leo** [comment]
記事を読んで理解できました．
